### ISSUE TITLE
infografiia

### ISSUE THREAD

**Issue by Anna-Aparicio** [SistemasTecTlaxiaco/infografia-Anna-Aparicio#2]
![infografia_analaura_IR](https://user-images.githubusercontent.com/80292858/112057895-79e17d80-8b1f-11eb-9790-8bff897f71bd.png)

**Comment by MarcosJonathan17** [comment]
Buena trabajo! La infografía esta bien estructurada tanto en el diseño como en la información.
Calificación: 20%

**Comment by MarcosJonathan17** [comment]
Buena trabajo! La infografía esta bien estructurada tanto en el diseño como en la información.
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
